CREATE TABLE `cal_note` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` VARBINARY(1000) DEFAULT NULL,
  `calendarid` INT NOT NULL,
  `calendar_object_id` INT UNSIGNED DEFAULT NULL,
  `uri` VARBINARY(1000) DEFAULT NULL,
  `star` TINYINT UNSIGNED DEFAULT '0',
  `description` TEXT COLLATE utf8mb4_unicode_ci,
  `trashed` TINYINT(1) DEFAULT '0',
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `summary` TEXT COLLATE utf8mb4_unicode_ci,
  `status` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Note status',
  `completed_date` DOUBLE(13,3) DEFAULT NULL,
  `scheduled_date` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_cal_note_calendarobjectid_id` (`calendar_object_id`) USING BTREE,
  KEY `idx_calnote_calendarid_uri` (`calendarid`,`uri`),
  FULLTEXT KEY `idx_calnote_summary_description` (`summary`,`description`),
  KEY `idx_calnote_uid` (`uid`),
  KEY `idx_calnote_uri` (`uri`),
  KEY `idx_is_trashed` (`trashed`),
  UNIQUE KEY `unique_idx_cal_note_uid_calendarid` (`uid`,`calendarid`) USING BTREE,
  CONSTRAINT `fk_cal_note_calendarobjectid_id` FOREIGN KEY (`calendar_object_id`) REFERENCES `calendarobjects` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci