CREATE TABLE `cal_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` VARBINARY(1000) DEFAULT NULL,
  `calendarid` INT NOT NULL,
  `calendar_object_id` INT UNSIGNED DEFAULT NULL,
  `uri` VARBINARY(1000) DEFAULT NULL,
  `summary` TEXT COLLATE utf8mb4_unicode_ci,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `location` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start` DOUBLE(13,3) DEFAULT NULL,
  `end` DOUBLE(13,3) DEFAULT NULL,
  `color` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allday` TINYINT(1) DEFAULT '0',
  `timezone` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alert` json DEFAULT NULL,
  `mi` TINYINT(1) DEFAULT '0',
  `repeat_rule` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recurid` DOUBLE(13,3) DEFAULT NULL,
  `exdates` json DEFAULT NULL,
  `trashed` TINYINT(1) DEFAULT '0',
  `invitee_uid` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_cal_event_calendarobjectid_id` (`calendar_object_id`) USING BTREE,
  KEY `idx_calevent_calendarid_uri` (`calendarid`,`uri`),
  KEY `idx_calevent_uid` (`uid`),
  KEY `idx_calevent_uri` (`uri`),
  KEY `idx_is_trashed` (`trashed`),
  UNIQUE KEY `unique_idx_cal_event_uid_calendarid_recurid` (`uid`,`calendarid`,`recurid`) USING BTREE,
  CONSTRAINT `fk_cal_event_calendarobjectid_id` FOREIGN KEY (`calendar_object_id`) REFERENCES `calendarobjects` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci