CREATE TABLE `calendars` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `synctoken` INT UNSIGNED NOT NULL DEFAULT '1',
  `components` VARBINARY(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1