CREATE TABLE `card_contact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` VARBINARY(1000) DEFAULT NULL,
  `addressbookid` INT NOT NULL,
  `card_id` INT UNSIGNED DEFAULT NULL,
  `uri` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `first_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `midle_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_address` json DEFAULT NULL,
  `company` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contact_avatar` TEXT COLLATE utf8mb4_unicode_ci,
  `phone` json DEFAULT NULL,
  `skype_call` json DEFAULT NULL,
  `skype_chat` json DEFAULT NULL,
  `vip` TINYINT UNSIGNED DEFAULT '0',
  `is_group` TINYINT UNSIGNED DEFAULT '0',
  `trashed` TINYINT(1) DEFAULT '0',
  `email_text` TEXT COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `card_contact_email_text_IDX` (`email_text`),
  KEY `fk_card_contact_uid_addressbookid` (`card_id`) USING BTREE,
  KEY `idx_cardcontact_addressbookid_uri` (`addressbookid`,`uri`),
  KEY `idx_cardcontact_uid` (`uid`),
  KEY `idx_is_trashed` (`trashed`),
  UNIQUE KEY `unique_idx_card_contact_uid_addressbookid` (`uid`,`addressbookid`) USING BTREE,
  CONSTRAINT `fk_card_contact_uid_addressbookid` FOREIGN KEY (`card_id`) REFERENCES `cards` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci