CREATE TABLE `chime_meeting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meeting_id` VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL,
  `external_meeting_id` VARCHAR(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'set conference id to this filed',
  `external_meeting_type` VARCHAR(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CONFERENCE',
  `media_region` VARCHAR(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `media_placement` json DEFAULT NULL,
  `start_time` INT DEFAULT NULL,
  `end_time` INT DEFAULT NULL,
  `spend_time` INT DEFAULT NULL COMMENT 'seconds',
  `status` enum('PENDING','STARTED','ENDED') COLLATE utf8mb4_general_ci DEFAULT 'PENDING',
  `channel_id` INT NOT NULL DEFAULT '0',
  `channel_title` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `host_user_id` BIGINT NOT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) NOT NULL,
  `capture_media_pipeline_arn` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `s3_bucket_arn` VARCHAR(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `summary_from_ai` TEXT COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`),
  KEY `chime_meeting_channel_id_IDX` (`channel_id`,`start_time`) USING BTREE,
  KEY `chime_meeting_external_meeting_id_IDX` (`external_meeting_id`,`external_meeting_type`) USING BTREE,
  KEY `chime_meeting_meeting_id_IDX` (`meeting_id`) USING BTREE,
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci