CREATE TABLE `collection_notification_member` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `collection_id` BIGINT NOT NULL DEFAULT '0',
  `channel_id` BIGINT NOT NULL DEFAULT '0',
  `calendarid` INT NOT NULL DEFAULT '0',
  `member_user_id` BIGINT UNSIGNED NOT NULL,
  `member_calendar_uri` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `member_email` VARCHAR(100) DEFAULT NULL,
  `access` TINYINT(1) NOT NULL DEFAULT '2',
  `owner_calendar_uri` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `owner_user_id` BIGINT DEFAULT NULL,
  `owner_email` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `fk_collection_id` BIGINT UNSIGNED DEFAULT NULL,
  `fk_channel_id` BIGINT DEFAULT NULL,
  `fk_cm_id` BIGINT UNSIGNED DEFAULT NULL,
  `fk_csm_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_date` DOUBLE(13,3) DEFAULT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '0',
  `partition_group` TINYINT GENERATED ALWAYS AS ((CASE WHEN ((`collection_id` > 0) AND (`channel_id` > 0)) THEN 1 WHEN ((`collection_id` = 0) AND (`channel_id` > 0)) THEN 2 ELSE 3 END)) STORED NOT NULL,
  PRIMARY KEY (`id`,`partition_group`),
  KEY `collection_notification_member_member_user_id_IDX` (`member_user_id`,`partition_group`) USING BTREE,
  KEY `comp_collection_channel` (`collection_id`,`channel_id`),
  KEY `idx_access` (`access`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_cnm_active_access` (`member_user_id`,`is_active`,`access`),
  KEY `idx_collection_id` (`collection_id`) /*!80000 INVISIBLE */,
  KEY `idx_owner_active_collection` (`owner_user_id`,`is_active`),
  KEY `idx_user_email` (`member_email`),
  KEY `idx_user_id` (`member_user_id`,`collection_id`),
  UNIQUE KEY `unq_user_collection_channel` (`member_user_id`,`collection_id`,`channel_id`,`partition_group`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1