CREATE TABLE `collection_notification_badge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT 'User id of member or owner collection',
  `email` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'Email of member or owner collection',
  `collection_id` BIGINT NOT NULL DEFAULT '0',
  `total` INT NOT NULL DEFAULT '0',
  `unread` INT NOT NULL DEFAULT '0',
  `object_type` VARBINARY(50) NOT NULL,
  `action` INT NOT NULL DEFAULT '0' COMMENT 'The action of the user changes the data of shared objects\n0: created (default )\n1: edited\n2: moved\n3: deleted\n4: completed (mark done) \n5: completed sub-task\n6: commented\n7: approved\n8: changed date\n9: changed time\n1:> changed location\n1:> rejected \n1:> started',
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT 'show/hide/archive/trash...',
  `assigner` VARCHAR(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `assignment` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0. not assign, 1. assigned to me, 2. assigned by me',
  `assignees` TEXT COLLATE utf8mb4_general_ci NOT NULL,
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  PRIMARY KEY (`id`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_comp` (`user_id`,`collection_id`,`object_type`,`action`,`assigner`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_email` (`email`),
  KEY `idx_on_object_type` (`object_type`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `uniq_badge` (`user_id`,`collection_id`,`object_type`,`assignment`,`assigner`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci