CREATE TABLE `collection_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT 'User id of member or owner collection',
  `email` VARCHAR(225) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `actor` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `collection_id` BIGINT NOT NULL DEFAULT '0',
  `comment_id` INT NOT NULL DEFAULT '0',
  `object_uid` VARBINARY(1000) NOT NULL,
  `sobject_uid` VARCHAR(100) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (CONVERT(`object_uid` USING cp1251)) VIRTUAL,
  `object_type` VARBINARY(50) NOT NULL,
  `sobject_type` VARCHAR(45) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (CONVERT(`object_type` USING cp1251)) VIRTUAL,
  `action` INT NOT NULL DEFAULT '0' COMMENT 'he action of the user changes the data of shared objects\n0: created (default )\n1: edited\n2: moved\n3: deleted\n4: completed (mark done) \n5: completed sub-task\n6: commented\n7: approved\n8: changed date\n9: changed time\n1:> changed location\n1:> rejected \n1:> started',
  `action_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `read` TINYINT(1) NOT NULL DEFAULT '0',
  `assignees` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'content changes',
  `tag_name` VARCHAR(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `kanban_id` BIGINT NOT NULL DEFAULT '0',
  `kanban_card_id` BIGINT NOT NULL DEFAULT '0',
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `channel_id` BIGINT NOT NULL DEFAULT '0',
  `emoji_unicode` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_email` TINYINT(1) DEFAULT NULL,
  `account_id` BIGINT NOT NULL DEFAULT '0',
  `category` TINYINT(1) NOT NULL DEFAULT '0',
  `actor_or_email` VARCHAR(255) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (ifnull(`actor`,`email`)) STORED,
  `noti_group` TINYINT(1) DEFAULT NULL,
  `is_reply` TINYINT(1) DEFAULT '0',
  `object_href` TEXT COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`,`object_uid`),
  KEY `collection_created_date_IDX` (`created_date`,`collection_id`) USING BTREE,
  KEY `collection_notification_actor_IDX` (`actor`) USING BTREE,
  KEY `collection_notification_created_date_IDX` (`created_date`,`channel_id`) USING BTREE,
  KEY `collection_notification_user_id_IDX` (`user_id`,`created_date`) USING BTREE,
  KEY `comp_idx_collection_channel` (`collection_id`,`channel_id`,`user_id`),
  KEY `comp_idx_notifications` (`id`,`user_id`,`collection_id`,`channel_id`,`object_type`,`action`,`created_date`,`updated_date`),
  KEY `idx_action` (`action`),
  KEY `idx_actor_or_email` (`actor_or_email`),
  KEY `idx_channel_collection_action` (`collection_id`,`action`,`channel_id`),
  KEY `idx_channel_id` (`channel_id`,`user_id`,`created_date`),
  KEY `idx_cn_created_collection_channel` (`created_date`,`collection_id`,`channel_id`,`user_id`),
  KEY `idx_cn_created_date_sort` (`collection_id`,`created_date`),
  KEY `idx_cn_query` (`channel_id`,`collection_id`,`object_type`,`action`,`id`),
  KEY `idx_collection_id` (`collection_id`,`created_date`,`user_id`),
  KEY `idx_collection_id_created_date` (`collection_id`,`created_date`),
  KEY `idx_comment_id` (`comment_id`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_email` (`email`),
  KEY `idx_object_type` (`object_type`),
  KEY `idx_object_type_and_object_uid` (`object_type`,`object_uid`),
  KEY `idx_object_uid` (`object_uid`),
  KEY `idx_on_object_type_and_object_uid_and` (`object_uid`,`object_type`),
  KEY `idx_sobject_type` (`sobject_type`),
  KEY `idx_sobject_uid` (`sobject_uid`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_user_id` (`user_id`),
  UNIQUE KEY `unq_email_action` (`noti_group`,`user_id`,`object_type`,`object_uid`,`action`,`action_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci