CREATE TABLE `demo_note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `star` TINYINT DEFAULT NULL,
  `created_at` DOUBLE DEFAULT NULL,
  `updated_at` DOUBLE DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1