CREATE TABLE `kanban_card` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `object_uid` VARBINARY(1000) NOT NULL,
  `object_type` VARBINARY(50) NOT NULL,
  `object_href` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `item_card_order` INT DEFAULT '0',
  `kanban_id` BIGINT NOT NULL DEFAULT '0',
  `account_id` BIGINT UNSIGNED DEFAULT '0',
  `order_number` DECIMAL(20,10) DEFAULT '0.0000000000',
  `order_update_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `is_trashed` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `recent_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  PRIMARY KEY (`id`),
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_kanban_id` (`kanban_id`),
  KEY `idx_on_user_id_and_kanban_id` (`user_id`,`kanban_id`),
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_user_id` (`user_id`),
  UNIQUE KEY `uniq_on_object_uid_and_object_type_and_kanban_id_and_account_id` (`object_uid`,`object_type`,`kanban_id`,`account_id`) USING BTREE,
  UNIQUE KEY `uniq_on_user_id_and_kanban_id_and_order_number` (`user_id`,`kanban_id`,`order_number`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci'