CREATE TABLE `realtime_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL DEFAULT '0',
  `uid` VARCHAR(300) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `from` VARCHAR(100) NOT NULL,
  `type` enum('NOTIFICATION','EVENT','CHAT') NOT NULL,
  `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `metadata` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'because have not function search messaege , so I design it json format',
  `send_type` enum('CHANNEL','USER','BROADCAST') NOT NULL,
  `to_channel` VARCHAR(300) DEFAULT NULL COMMENT 'channel name',
  `parent_uid` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `qos` TINYINT NOT NULL DEFAULT '0' COMMENT '0: only send 1 time, 1: alway send unit user readed',
  `delay` INT NOT NULL DEFAULT '0' COMMENT 'time second delay send',
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT '1: sent; 0: unsend',
  `sent_time` DOUBLE(13,3) DEFAULT NULL,
  `reaction_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) NOT NULL,
  `deleted_date` DOUBLE(13,3) DEFAULT NULL,
  `content_marked` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `message_marked` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `reply_number` INT NOT NULL DEFAULT '0',
  `mention_emails` TEXT,
  `deleted_message_type` VARCHAR(45) DEFAULT NULL,
  `migrate_to_es` TINYINT(1) NOT NULL DEFAULT '0',
  `linked_object_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `is_pending` TINYINT DEFAULT NULL COMMENT 'NULL=not pending/completed, 1=pending file upload',
  PRIMARY KEY (`id`),
  KEY `idx_reaction_time` (`reaction_time`),
  KEY `idx_to_channel_and_created_date` (`to_channel`,`created_date`),
  KEY `idx_type` (`type`),
  KEY `idx_updated_date` (`updated_date`),
  UNIQUE KEY `notification_UN` (`uid`),
  KEY `realtime_message_created_date_IDX` (`created_date`) USING BTREE,
  KEY `realtime_message_parent_uid_IDX` (`parent_uid`) USING BTREE,
  KEY `realtime_message_status_IDX` (`status`) USING BTREE,
  KEY `realtime_message_to_channel_IDX` (`to_channel`) USING BTREE,
  KEY `realtime_message_type_IDX` (`type`) USING BTREE /*!80000 INVISIBLE */
) ENGINE=InnoDB DEFAULT CHARSET=latin1