CREATE TABLE `realtime_chat_channel_user_last_seen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `channel_id` INT NOT NULL DEFAULT '0',
  `channel_name` VARCHAR(100) NOT NULL,
  `last_seen` DOUBLE(13,3) NOT NULL,
  `last_message_uid` VARCHAR(100) NOT NULL,
  `last_message_created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `channel_last_message_uid` VARCHAR(100) DEFAULT NULL,
  `channel_last_message_created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `unread` INT NOT NULL DEFAULT '0',
  `remine` INT DEFAULT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) NOT NULL,
  `disabled` TINYINT(1) NOT NULL DEFAULT '0',
  `mentioned_from_last_seen` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_channel_id_and_username` (`channel_id`,`email`) USING BTREE,
  KEY `idx_channel_name` (`channel_name`),
  KEY `idx_channel_name_and_email` (`channel_name`,`email`),
  KEY `idx_disabled` (`disabled`),
  KEY `idx_email_disable_unread` (`email`,`disabled`,`unread`),
  KEY `idx_last_msg_created` (`channel_last_message_created_date`) USING BTREE,
  KEY `idx_last_msg_uid` (`last_message_uid`),
  KEY `idx_last_msg_uid_channel` (`channel_last_message_uid`),
  KEY `idx_last_seen` (`last_seen`),
  KEY `idx_updated_date` (`updated_date`),
  UNIQUE KEY `realtime_chat_channel_user_last_seen_UN` (`email`,`channel_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1