CREATE TABLE `report_cached_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `account_3rd` INT NOT NULL DEFAULT '0',
  `account_3rd_emails` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `account_type` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `storage` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `storage_total` BIGINT UNSIGNED NOT NULL,
  `groups` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `sub_id` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subs_type` INT DEFAULT NULL,
  `order_number` INT DEFAULT NULL,
  `subs_current_date` DOUBLE(13,3) DEFAULT NULL,
  `last_used_date` DOUBLE(13,3) DEFAULT NULL,
  `join_date` DOUBLE(13,3) DEFAULT NULL,
  `next_renewal` DOUBLE(13,3) DEFAULT NULL,
  `disabled` TINYINT UNSIGNED DEFAULT '0',
  `deleted` TINYINT UNSIGNED DEFAULT '0',
  `addition_info` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_migrate_status` TINYINT UNSIGNED DEFAULT '1',
  `platform` json DEFAULT NULL,
  `old_platform` json DEFAULT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  FULLTEXT KEY `idx_account_3rd_emails` (`account_3rd_emails`),
  FULLTEXT KEY `idx_groups` (`groups`),
  KEY `idx_join_date` (`join_date`),
  KEY `idx_last_used_date` (`last_used_date`),
  KEY `idx_next_renewal` (`next_renewal`),
  KEY `idx_storage_total` (`storage_total`),
  KEY `idx_subID` (`sub_id`),
  KEY `idx_subs_type` (`subs_type`),
  KEY `idx_user_id` (`user_id`),
  UNIQUE KEY `uniq_email` (`email`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci