CREATE TABLE `setting` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `default_cal` VARCHAR(255) NOT NULL DEFAULT '',
  `timezone` VARCHAR(255) NOT NULL DEFAULT 'America/Chicago',
  `tz_city` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `working_time` json NOT NULL,
  `event_duration` INT NOT NULL DEFAULT '0',
  `alert_default` INT NOT NULL DEFAULT '0',
  `snooze_default` INT NOT NULL DEFAULT '15',
  `timezone_support` TINYINT NOT NULL DEFAULT '0',
  `task_duration` INT NOT NULL DEFAULT '0',
  `deadline` INT NOT NULL DEFAULT '0',
  `due_task` INT NOT NULL DEFAULT '0',
  `number_stask` INT NOT NULL DEFAULT '0',
  `total_duration` INT NOT NULL DEFAULT '0',
  `buffer_time` INT NOT NULL DEFAULT '0',
  `hide_stask` TINYINT NOT NULL DEFAULT '0',
  `background` INT NOT NULL DEFAULT '0',
  `short_duration` INT NOT NULL DEFAULT '30',
  `medium_duration` INT NOT NULL DEFAULT '60',
  `long_duration` INT NOT NULL DEFAULT '180',
  `default_folder` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `calendar_color` VARCHAR(50) NOT NULL DEFAULT '',
  `folder_color` VARCHAR(50) NOT NULL DEFAULT '',
  `navbar_system` TEXT NOT NULL,
  `navbar_custom` TEXT NOT NULL,
  `infobox` TEXT NOT NULL,
  `infobox_order` json NOT NULL,
  `contact_display_name` INT NOT NULL DEFAULT '0',
  `contact_display_inlist` INT NOT NULL DEFAULT '0',
  `m_ade` TINYINT NOT NULL DEFAULT '1',
  `m_event` TINYINT NOT NULL DEFAULT '1',
  `m_task` TINYINT NOT NULL DEFAULT '1',
  `m_stask` TINYINT NOT NULL DEFAULT '1',
  `m_done_task` TINYINT NOT NULL DEFAULT '1',
  `m_due_task` TINYINT NOT NULL DEFAULT '1',
  `m_note` TINYINT NOT NULL DEFAULT '1',
  `dw_due_task` TINYINT NOT NULL DEFAULT '1',
  `dw_ade` TINYINT NOT NULL DEFAULT '1',
  `dw_done_task` TINYINT NOT NULL DEFAULT '1',
  `dw_note` TINYINT NOT NULL DEFAULT '1',
  `del_warning` TINYINT NOT NULL DEFAULT '1',
  `hide_future_task` TINYINT NOT NULL DEFAULT '0',
  `ics_attachment` TINYINT NOT NULL DEFAULT '1',
  `mail_auto_download_check` INT NOT NULL DEFAULT '0',
  `mail_num_time_dont_auto_download` INT NOT NULL DEFAULT '6',
  `mail_time_dont_auto_download` INT NOT NULL DEFAULT '1',
  `mail_display_act_button` INT NOT NULL DEFAULT '0',
  `number_mail_lines_preview` INT NOT NULL DEFAULT '4',
  `mail_moving_check` INT NOT NULL DEFAULT '1',
  `mail_size_dont_download` INT NOT NULL DEFAULT '10',
  `show_nutshell` TINYINT NOT NULL DEFAULT '1',
  `show_bg_by_weather` TINYINT NOT NULL DEFAULT '0',
  `week_start` INT NOT NULL DEFAULT '0',
  `send_and_track` INT NOT NULL DEFAULT '2',
  `action_icon` INT NOT NULL DEFAULT '0',
  `emailbox_order` json NOT NULL,
  `alert_before` INT NOT NULL DEFAULT '60',
  `send_invite` TINYINT NOT NULL DEFAULT '0',
  `from_email` VARCHAR(255) NOT NULL DEFAULT '',
  `default_alert_ade` INT DEFAULT '0',
  `default_alert_todo` INT DEFAULT '0',
  `default_milestone_alert` INT DEFAULT '0',
  `avatar` MEDIUMTEXT NOT NULL,
  `assign_tz_eve` TINYINT NOT NULL DEFAULT '1',
  `m_show` INT NOT NULL DEFAULT '23',
  `dw_show` INT NOT NULL DEFAULT '23',
  `agenda_show` INT NOT NULL DEFAULT '23',
  `move_email` INT NOT NULL DEFAULT '1',
  `noti_bear_track` INT NOT NULL DEFAULT '0',
  `state` INT NOT NULL DEFAULT '0',
  `recent_tz` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `order_url` MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `order_todo` MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `keep_state` MEDIUMTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `omni_cal_id` VARCHAR(500) NOT NULL DEFAULT '',
  `url_option` INT NOT NULL DEFAULT '0',
  `init_planner_st` INT NOT NULL DEFAULT '0',
  `order_storyboard` MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `show_star` INT NOT NULL DEFAULT '0',
  `signature` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `filing_email` INT DEFAULT '0',
  `show_date_timezone` TINYINT DEFAULT '0',
  `show_feedback` TINYINT DEFAULT '1',
  `theme_mode` TINYINT NOT NULL DEFAULT '0' COMMENT '0 (light - default), = 1: dark',
  `scroll_24h` TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT 'Enable "Working Hour" mode',
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `hide_done_todo` TINYINT(1) NOT NULL DEFAULT '1',
  `indicate_done_todo` TINYINT(1) NOT NULL DEFAULT '0',
  `note_ask` TINYINT(1) NOT NULL DEFAULT '0',
  `todo_ask` TINYINT(1) NOT NULL DEFAULT '0',
  `note_collection_id` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `todo_collection_id` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `notification_clean_date` INT NOT NULL DEFAULT '2592000' COMMENT 'DEFAULT: 43200 = 1 MONTH IN SECOND',
  `clean_after_opening` TINYINT(1) NOT NULL DEFAULT '1',
  `todo_move_mail_noti` TINYINT NOT NULL DEFAULT '1',
  `event_move_mail_noti` TINYINT NOT NULL DEFAULT '1',
  `call_notification` TINYINT NOT NULL DEFAULT '1',
  `chat_notification` TINYINT NOT NULL DEFAULT '1',
  `mail_notification` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_notification_clean_date` (`notification_clean_date`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='utf8_unicode_ci'