CREATE TABLE `sort_agile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `collection_id` BIGINT NOT NULL DEFAULT '0',
  `status` enum('CURRENT','BACKLOG','ICEBOX') DEFAULT NULL,
  `calendar_uri` VARCHAR(255) NOT NULL DEFAULT '',
  `user_id` BIGINT UNSIGNED NOT NULL,
  `account_id` BIGINT UNSIGNED DEFAULT '0',
  `object_uid` VARBINARY(1000) NOT NULL,
  `object_type` VARBINARY(50) NOT NULL,
  `object_href` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `order_number` DECIMAL(20,10) DEFAULT '0.0000000000',
  `server_order_number` DECIMAL(20,10) DEFAULT NULL,
  `order_update_time` DOUBLE(13,3) DEFAULT '0.000',
  `server_order_update_time` DOUBLE(13,3) DEFAULT NULL,
  `action_time` DOUBLE(13,3) DEFAULT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_collection_id` (`collection_id`) USING BTREE,
  KEY `idx_collection_id_order_number` (`collection_id`,`order_number`),
  KEY `idx_on_object_type_and_object_uid` (`object_type`,`object_uid`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  UNIQUE KEY `unq_collection_and_object` (`user_id`,`collection_id`,`object_type`,`object_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1