import { Page, TestInfo } from '@playwright/test';
import fs from 'fs';
import path from 'path';

const BUG_REPORT_PATH = path.join(__dirname, '../../test-results/BUG_REPORT.md');
const SCREENSHOTS_DIR = path.join(__dirname, '../../test-results/screenshots');

function ensureDirs() {
  const resultsDir = path.join(__dirname, '../../test-results');
  if (!fs.existsSync(resultsDir)) fs.mkdirSync(resultsDir, { recursive: true });
  if (!fs.existsSync(SCREENSHOTS_DIR)) fs.mkdirSync(SCREENSHOTS_DIR, { recursive: true });
}

function initBugReport() {
  ensureDirs();
  if (!fs.existsSync(BUG_REPORT_PATH)) {
    fs.writeFileSync(
      BUG_REPORT_PATH,
      `# 🐛 Automated Bug Report — TheAndb Desktop E2E\n\n> Generated by Playwright on ${new Date().toISOString()}\n\n---\n\n`,
    );
  }
}

let bugCounter = 0;

function writeBug({
  testName,
  specFile,
  error,
  screenshotPath,
  consoleErrors,
}: {
  testName: string;
  specFile: string;
  error: string;
  screenshotPath?: string;
  consoleErrors: string[];
}) {
  initBugReport();
  bugCounter++;
  const bugId = `BUG-${String(bugCounter).padStart(3, '0')}`;
  const screenshotRef = screenshotPath
    ? `![screenshot](${path.relative(path.dirname(BUG_REPORT_PATH), screenshotPath)})`
    : '_No screenshot_';

  const consoleBlock =
    consoleErrors.length > 0
      ? '```\n' + consoleErrors.join('\n') + '\n```'
      : '_None captured_';

  const severity =
    error.includes('TimeoutError') ? '🟡 Medium (Selector / Timing)'
    : error.includes('ERR_IPC') ? '🔴 High (IPC / Crash)'
    : error.includes('net::ERR') ? '🔴 High (Network)'
    : '⚪ Unknown';

  const entry = `
## ${bugId} — ${testName}

- **Date:** ${new Date().toISOString().split('T')[0]}
- **Spec:** \`${specFile}\`
- **Error:** \`${error.slice(0, 300)}\`
- **Severity:** ${severity}
- **Screenshot:** ${screenshotRef}
- **Console Errors:**
${consoleBlock}

---
`;

  fs.appendFileSync(BUG_REPORT_PATH, entry);
  console.log(`[BugReporter] 📝 Logged ${bugId}: ${testName}`);
}

export class BugReporter {
  private capturedErrors: string[] = [];

  constructor(private window: Page, private testInfo: TestInfo) {}

  captureConsoleError(msg: string) {
    this.capturedErrors.push(msg);
  }

  async reportIfFailed() {
    if (this.testInfo.status !== this.testInfo.expectedStatus) {
      let screenshotPath: string | undefined;

      const safeName = this.testInfo.title.replace(/[^a-z0-9]/gi, '-').toLowerCase();
      const resultsDir = path.dirname(BUG_REPORT_PATH);
      if (!fs.existsSync(SCREENSHOTS_DIR)) fs.mkdirSync(SCREENSHOTS_DIR, { recursive: true });
      
      screenshotPath = path.join(SCREENSHOTS_DIR, `${safeName}-${Date.now()}.png`);
      
      try {
        await this.window.screenshot({ path: screenshotPath, fullPage: true });
      } catch (err) {
        console.error('[BugReporter] Failed to take screenshot:', err);
        screenshotPath = undefined;
      }

      writeBug({
        testName: this.testInfo.title,
        specFile: path.basename(this.testInfo.file),
        error: this.testInfo.error?.message || 'Unknown error',
        screenshotPath,
        consoleErrors: this.capturedErrors,
      });
    }
  }
}
