CREATE TABLE `access_token` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `app_id` VARCHAR(255) NOT NULL,
  `device_uid` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `access_token` TINYBLOB NOT NULL,
  `access_token_iv` TINYBLOB NOT NULL,
  `refresh_token` TINYBLOB NOT NULL,
  `refresh_token_iv` TINYBLOB NOT NULL,
  `previous_refresh_token` TINYBLOB,
  `scope` TEXT,
  `token_type` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(255) DEFAULT '',
  `ip` VARCHAR(45) DEFAULT '',
  `is_revoked` TINYINT UNSIGNED DEFAULT '0',
  `device_token` VARCHAR(255) DEFAULT NULL,
  `expires_in` DOUBLE NOT NULL,
  `expires_in_refresh_token` DOUBLE NOT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `access_token_device_token_IDX` (`device_token`) USING BTREE,
  KEY `idx_access_token` (`access_token`(255)),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_email` (`email`),
  KEY `idx_expires_in` (`expires_in`),
  KEY `idx_on_app_id_and_device_uid` (`app_id`,`device_uid`),
  KEY `idx_on_is_revoked_and_device_uid_and_access_token` (`is_revoked`,`device_uid`,`access_token`(255)),
  KEY `idx_on_user_id_and_app_id_and_device_uid` (`user_id`,`app_id`,`device_uid`),
  KEY `idx_refresh_token` (`refresh_token`(255)) USING BTREE,
  KEY `idx_user_id` (`user_id`),
  UNIQUE KEY `uniq_access_token_iv` (`access_token_iv`(64)),
  UNIQUE KEY `uniq_on_device_uid_and_access_token` (`device_uid`,`access_token`(255)),
  UNIQUE KEY `uniq_on_device_uid_and_refresh_token` (`device_uid`,`refresh_token`(255)),
  UNIQUE KEY `uniq_refresh_token_iv` (`refresh_token_iv`(64))
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci'