CREATE TABLE `apple_webhook_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request_id` VARCHAR(255) NOT NULL,
  `timestamp` VARCHAR(255) NOT NULL,
  `method` VARCHAR(10) NOT NULL,
  `path` VARCHAR(500) NOT NULL,
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `processed` TINYINT(1) DEFAULT '1',
  `notification_type` VARCHAR(100) NOT NULL,
  `notification_uuid` VARCHAR(255) NOT NULL,
  `subtype` VARCHAR(100) DEFAULT NULL,
  `environment` VARCHAR(50) NOT NULL,
  `signed_date` VARCHAR(255) NOT NULL,
  `app_metadata` json DEFAULT NULL,
  `renewal_info` json DEFAULT NULL,
  `transaction_info` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_environment` (`environment`),
  KEY `idx_method` (`method`),
  KEY `idx_notification_type` (`notification_type`),
  KEY `idx_notification_uuid` (`notification_uuid`),
  KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1