CREATE TABLE `cal_todo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` VARBINARY(1000) DEFAULT NULL,
  `calendarid` INT NOT NULL,
  `calendar_object_id` INT UNSIGNED DEFAULT NULL,
  `uri` VARBINARY(1000) DEFAULT NULL,
  `star` TINYINT UNSIGNED DEFAULT '0',
  `description` TEXT COLLATE utf8mb4_unicode_ci,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `summary` TEXT COLLATE utf8mb4_unicode_ci,
  `location` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_date` DOUBLE(13,3) DEFAULT NULL,
  `due_date` DOUBLE(13,3) DEFAULT NULL,
  `start` DOUBLE(13,3) DEFAULT NULL,
  `duration` BIGINT DEFAULT '0',
  `subtasks` json DEFAULT NULL,
  `alert` json DEFAULT NULL,
  `stodo` TINYINT UNSIGNED DEFAULT '0',
  `trashed` TINYINT(1) DEFAULT '0',
  `repeat_rule` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recurid` DOUBLE(13,3) DEFAULT NULL,
  `exdates` json DEFAULT NULL,
  `status` VARCHAR(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'status of todo',
  `assigned` TINYINT(1) DEFAULT '0' COMMENT 'Assign Todo',
  `priority` TINYINT DEFAULT NULL,
  `organizer` VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `category` TINYINT DEFAULT NULL,
  `state` VARCHAR(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `review` json DEFAULT NULL,
  `blocker` json DEFAULT NULL,
  `point` TINYINT DEFAULT NULL,
  `assignee` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_cal_todo_calendarobjectid_id` (`calendar_object_id`) USING BTREE,
  KEY `idx_caltodo_calendarid_uri` (`calendarid`,`uri`),
  FULLTEXT KEY `idx_caltodo_summary_description` (`summary`,`description`),
  KEY `idx_caltodo_uid` (`uid`),
  KEY `idx_caltodo_uri` (`uri`),
  KEY `idx_is_trashed` (`trashed`),
  UNIQUE KEY `uniq_on_uid_and_calendarid_and_recurid` (`uid`,`calendarid`,`recurid`) USING BTREE,
  CONSTRAINT `fk_cal_todo_calendarobjectid_id` FOREIGN KEY (`calendar_object_id`) REFERENCES `calendarobjects` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci