CREATE TABLE `collection` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `calendar_uri` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `parent_id` BIGINT NOT NULL DEFAULT '0',
  `root_id` BIGINT NOT NULL DEFAULT '0',
  `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` BIGINT DEFAULT NULL,
  `realtime_channel` VARCHAR(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '',
  `color` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `type` TINYINT(1) NOT NULL DEFAULT '0',
  `kind` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1 - normal\n2 - epic',
  `info_card_order` INT NOT NULL DEFAULT '0',
  `current_mode` INT NOT NULL DEFAULT '0',
  `alerts` json DEFAULT NULL,
  `order_storyboard` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `order_kanban` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `state` TINYINT UNSIGNED DEFAULT '1',
  `flag` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `is_hide` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `is_expand` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `view_mode` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `view_sort` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `kanban_mode` TINYINT(1) DEFAULT '0',
  `icon` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `due_date` DOUBLE(13,3) DEFAULT '0.000',
  `recent_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `is_trashed` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `pt_project_id` INT DEFAULT NULL,
  `description` TEXT,
  `show_archive_sub_col` TINYINT(1) DEFAULT '1',
  `archive_status` TINYINT(1) DEFAULT NULL,
  `archived_time` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_calendar_id` (`calendar_uri`),
  UNIQUE KEY `idx_channel_id` (`channel_id`),
  FULLTEXT KEY `idx_collection_name` (`name`),
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_on_id_and_user_id` (`id`,`user_id`),
  KEY `idx_on_user_id_and_parent_id` (`user_id`,`parent_id`),
  KEY `idx_pt_project` (`pt_project_id`),
  KEY `idx_relative_and_trash` (`user_id`,`root_id`,`parent_id`,`is_trashed`),
  KEY `idx_root_id` (`root_id`),
  KEY `idx_trash_type` (`type`,`is_trashed`),
  KEY `idx_type` (`type`) USING BTREE,
  KEY `idx_user_calendar_uri` (`user_id`,`calendar_uri`),
  KEY `idx_user_id` (`user_id`,`id`),
  KEY `idx_user_id_and_type` (`user_id`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='utf8_unicode_ci'