CREATE TABLE `conference_history` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `member_id` BIGINT NOT NULL,
  `invitee` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_number` VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `start_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000' COMMENT 'start time of the call',
  `end_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000' COMMENT 'end time of the call',
  `type` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '1 = video, 2 = audio ',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'the status of the call',
  `organizer` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attendees` TEXT COLLATE utf8mb4_unicode_ci,
  `action_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `conference_meeting_id` BIGINT NOT NULL DEFAULT '0',
  `meeting_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `external_meeting_id` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_reply` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 = receive, 1 = reply',
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `is_calling` TINYINT DEFAULT '1',
  `created_by_server` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `conference_history_phone_number_IDX` (`phone_number`) USING BTREE,
  KEY `conference_history_start_time_IDX` (`start_time`) USING BTREE,
  KEY `idx_conference_meeting_id` (`conference_meeting_id`),
  KEY `idx_meeting_id` (`meeting_id`,`created_date` DESC),
  KEY `idx_member_id` (`member_id`,`meeting_id`),
  KEY `idx_on_user_id_member_id_and_start_time` (`user_id`,`member_id`,`start_time`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_user_id_and_member_id` (`user_id`,`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'