CREATE TABLE `conference_member` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_history_id` BIGINT NOT NULL DEFAULT '0',
  `user_id` BIGINT UNSIGNED NOT NULL,
  `channel_id` BIGINT UNSIGNED NOT NULL,
  `uid` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_number` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `is_creator` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `title` VARCHAR(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` TEXT COLLATE utf8mb4_unicode_ci,
  `avatar` TEXT COLLATE utf8mb4_unicode_ci,
  `vip` TINYINT(1) NOT NULL DEFAULT '0',
  `star_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `chat_url` VARCHAR(2000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `member_arn` VARCHAR(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `revoke_time` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `join_time` DOUBLE(13,3) DEFAULT '0.000',
  `view_chat_history` TINYINT(1) NOT NULL DEFAULT '1',
  `missed_calls` INT NOT NULL DEFAULT '0',
  `last_seen_call` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `meeting_id` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'The last seen meeting id',
  `last_missed_call` DOUBLE(13,3) NOT NULL,
  `notification_chat` TINYINT(1) NOT NULL DEFAULT '2',
  `notification_call` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `comp_creator` (`id`,`email`,`is_creator`,`revoke_time`),
  KEY `idx_channel_id` (`channel_id`) USING BTREE,
  KEY `idx_conference_member_sort` (`user_id`,`channel_id`,`id`,`updated_date`,`created_date`),
  KEY `idx_conference_member_vip` (`user_id`,`vip`,`revoke_time`,`channel_id`),
  KEY `idx_email` (`email`),
  KEY `idx_last_history_id` (`last_history_id`),
  KEY `idx_revoke_time` (`revoke_time`) USING BTREE,
  KEY `idx_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_id_and_revoke_time_and_channel_id` (`user_id`,`revoke_time`,`channel_id`),
  KEY `idx_vip` (`vip`),
  UNIQUE KEY `uniq_on_conference_id_and_user_id_and_phone` (`channel_id`,`phone_number`),
  UNIQUE KEY `uniq_on_conference_id_and_user_id_and_user_name` (`user_id`,`email`,`channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'