CREATE TABLE `kanban` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `collection_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(5000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_number` DECIMAL(20,10) DEFAULT '0.0000000000',
  `archive_status` INT DEFAULT '0',
  `order_kbitem` TEXT COLLATE utf8mb4_unicode_ci,
  `order_update_time` DOUBLE(14,4) NOT NULL DEFAULT '0.0000',
  `show_done_todo` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `add_new_obj_type` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `sort_by_type` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `archived_time` DOUBLE(13,3) DEFAULT '0.000',
  `kanban_type` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `is_trashed` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `created_date` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `updated_date` DOUBLE(14,4) NOT NULL DEFAULT '0.0000',
  `kanban_status_value` INT NOT NULL DEFAULT '-1',
  PRIMARY KEY (`id`),
  KEY `idx_archive_status` (`archive_status`),
  KEY `idx_collection_id` (`collection_id`),
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_kanban_updated_date` (`updated_date`) USING BTREE,
  KEY `idx_name` (`name`(768)),
  KEY `idx_on_user_id_and_collection_id` (`user_id`,`collection_id`,`kanban_type`,`is_trashed`),
  KEY `idx_on_user_id_and_collection_id_and_type` (`user_id`,`collection_id`,`kanban_type`),
  UNIQUE KEY `uniq_on_user_id_and_collection_id_and_order_number` (`user_id`,`collection_id`,`order_number`),
  UNIQUE KEY `uniq_on_user_id_and_collection_id_and_updated_date` (`user_id`,`updated_date`,`collection_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='utf8mb4_unicode_ci'