CREATE TABLE `linked_collection_object` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `collection_id` BIGINT UNSIGNED NOT NULL,
  `account_id` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `object_uid` VARBINARY(1000) NOT NULL,
  `object_type` VARBINARY(50) NOT NULL,
  `object_href` TEXT COLLATE utf8mb4_unicode_ci,
  `is_trashed` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `email_time` DOUBLE(13,3) DEFAULT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `pt_story_id` INT DEFAULT NULL,
  PRIMARY KEY (`collection_id`,`account_id`,`object_uid`),
  KEY `idx_account_collection_object` (`collection_id`,`account_id`,`object_type`,`object_uid`),
  KEY `idx_collection_id` (`collection_id`),
  UNIQUE KEY `idx_id_inc` (`id`) USING BTREE,
  KEY `idx_is_trashed` (`is_trashed`),
  KEY `idx_object_uid` (`object_uid`) USING BTREE,
  KEY `idx_on_user_id_and_account_id` (`user_id`,`account_id`),
  KEY `idx_pt_story_id` (`pt_story_id`),
  KEY `idx_updated_date` (`updated_date`),
  KEY `idx_user_collection_object` (`collection_id`,`user_id`,`object_type`),
  KEY `idx_user_id_trashed` (`id`,`user_id`,`is_trashed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci