CREATE TABLE `storage_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `path` VARCHAR(4000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `path_hash` VARCHAR(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `parent_uid` VARCHAR(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `name` VARCHAR(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `size` BIGINT DEFAULT NULL,
  `mtime` BIGINT DEFAULT NULL,
  `encrypted` TINYINT(1) DEFAULT NULL,
  `unencrypted_size` BIGINT DEFAULT NULL,
  `etag` VARCHAR(40) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `checksum` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `mimetype` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `owner` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_linked` TINYINT(1) NOT NULL DEFAULT '0',
  `is_available` TINYINT DEFAULT NULL,
  `is_trashed` TINYINT DEFAULT '0',
  `collection` VARCHAR(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_by` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_date` DOUBLE DEFAULT NULL,
  `updated_date` DOUBLE DEFAULT NULL,
  `deleted_date` DOUBLE DEFAULT NULL,
  `is_shared` TINYINT(1) NOT NULL DEFAULT '0',
  `has_cache` TINYINT(1) NOT NULL DEFAULT '0',
  `has_thumbnail` TINYINT(1) NOT NULL DEFAULT '0',
  `thumb_size` BIGINT DEFAULT NULL,
  `comp_size` BIGINT DEFAULT NULL,
  `is_private` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `storage_file_collection_IDX` (`collection`) USING BTREE,
  KEY `storage_file_is_shared_IDX` (`is_shared`) USING BTREE,
  KEY `storage_file_owner_idx` (`owner`) USING BTREE,
  KEY `storage_file_uid_IDX` (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci