CREATE TABLE `third_party_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `server_income` VARCHAR(255) NOT NULL DEFAULT '',
  `user_income` VARCHAR(255) NOT NULL DEFAULT '',
  `pass_income` VARCHAR(1000) NOT NULL DEFAULT '',
  `port_income` VARCHAR(255) NOT NULL DEFAULT '',
  `use_ssl_income` INT DEFAULT '0',
  `type_income` INT DEFAULT '0',
  `server_smtp` VARCHAR(255) DEFAULT '',
  `user_smtp` VARCHAR(255) DEFAULT '',
  `pass_smtp` VARCHAR(1000) DEFAULT '',
  `port_smtp` VARCHAR(255) DEFAULT '',
  `use_ssl_smtp` INT NOT NULL DEFAULT '0',
  `auth_type_smtp` INT NOT NULL DEFAULT '0',
  `server_caldav` VARCHAR(255) DEFAULT '',
  `server_path_caldav` VARCHAR(255) DEFAULT '',
  `port_caldav` VARCHAR(255) DEFAULT '',
  `use_ssl_caldav` INT DEFAULT '0',
  `use_kerberos_caldav` INT DEFAULT '0',
  `auth_type` INT DEFAULT '0',
  `account_type` INT DEFAULT '0',
  `account_sync` json DEFAULT NULL,
  `auth_key` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `auth_token` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `full_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `refresh_token` TEXT NOT NULL,
  `provider` VARCHAR(255) DEFAULT '',
  `icloud_user_id` VARCHAR(255) NOT NULL DEFAULT '',
  `third_party_user_id` VARCHAR(255) NOT NULL DEFAULT '',
  `user_caldav` VARCHAR(255) NOT NULL DEFAULT '',
  `email_address` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `token_expire` INT DEFAULT '0',
  `activated_push` INT NOT NULL DEFAULT '0',
  `signature` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  UNIQUE KEY `uniq_on_user_id_and_user_income_and_account_type` (`user_id`,`user_income`,`account_type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='utf8_unicode_ci'