CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `digesta1` VARCHAR(255) NOT NULL,
  `digestb` VARCHAR(255) DEFAULT NULL,
  `domain_id` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `password2` VARCHAR(255) NOT NULL,
  `appreg_id` VARCHAR(255) NOT NULL DEFAULT '',
  `fullname` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rsa` TEXT NOT NULL,
  `description` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `secondary_email` VARCHAR(255) NOT NULL DEFAULT '',
  `birthday` VARCHAR(255) NOT NULL DEFAULT '',
  `gender` TINYINT(1) NOT NULL DEFAULT '0',
  `country` VARCHAR(255) NOT NULL DEFAULT '',
  `phone_number` VARCHAR(50) NOT NULL DEFAULT '',
  `country_code` VARCHAR(25) NOT NULL DEFAULT '',
  `token` VARCHAR(500) NOT NULL DEFAULT '',
  `token_expire` DOUBLE(13,3) NOT NULL DEFAULT '0.000',
  `question` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `answer` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `active_sec_email` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `max_uid` INT NOT NULL DEFAULT '0',
  `activated_push` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `quota_limit_bytes` BIGINT UNSIGNED NOT NULL DEFAULT '0',
  `disabled` TINYINT(1) NOT NULL DEFAULT '0',
  `created_date` DOUBLE(13,3) NOT NULL,
  `updated_date` DOUBLE(13,3) DEFAULT NULL,
  `private_key_1` TEXT,
  `private_key_2` TEXT,
  `public_key` TEXT,
  `migrated` TINYINT DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_domain_id` (`domain_id`),
  KEY `idx_email` (`email`) USING BTREE,
  FULLTEXT KEY `idx_fulltext_email` (`email`),
  KEY `idx_on_token_and_token_expire` (`token`,`token_expire`),
  FULLTEXT KEY `idx_username` (`username`),
  UNIQUE KEY `uniq_username` (`username`),
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`domain_id`) REFERENCES `virtual_domain` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='utf8_unicode_ci'